### ISSUE TITLE
Would you like any help?

### ISSUE THREAD

**Issue by kingcodefish** [BlazeProgramming/CadettsLibrary#6]
Just wondering what you're trying to accomplish ATM and see if you need any help. Also, why you no follow me? ;(

**Comment by CosignCosine** [comment]
I didn't think to :P

**Comment by CosignCosine** [comment]
You could help, any suggestions?

**Comment by kingcodefish** [comment]
You still no follow me, and yeah, let me check it out. Would you be interested if SoS started back up?

**Comment by CosignCosine** [comment]
I could be, but I wasn't really helping much ;)

**Comment by kingcodefish** [comment]
If you're interested, check my latest projects. You may scream for joy if you find the right one.

**Comment by kingcodefish** [comment]
You're taking forever, let me help you there: https://github.com/KCF-AlexT-Eytukan/star-wars-the-final-frontier

**Comment by CosignCosine** [comment]
Did I mention I'm at school? :P

**Comment by kingcodefish** [comment]
No you didn't, but I got that feeling.

**Comment by CosignCosine** [comment]
Haha!
I saw it already, looks cool!
Today, I got a request to join a programming team IRL, so depending on how that goes, I may not be as active here on KA or GitHub.

**Comment by kingcodefish** [comment]
Wait, what? In your school? Depends on what they're asking you to program. :/

**Comment by kingcodefish** [comment]
BTW, https://www.khanacademy.org/computer-programming/star-wars-the-final-frontier/6136022677454848

**Comment by AlexT101** [comment]
Hey, Guys - Just wanted you to know, I perfected "AlexT's Random Comment 1.0", and used it to replace the original program.

**Comment by kingcodefish** [comment]
Okay
